[Interface]
PrivateKey = QCVIPH5n6G+/UA4qhYz78C65HHV2quyJAWtD4ibgBlU=
Address = 10.0.0.1/24
ListenPort = 51820
DNS = 1.1.1.1
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
[Peer]
PublicKey = Xhq9elWFz8ASFOipVPj1U2NeG7osC+XO6rmTDaRbBD8=
AllowedIPs = 10.0.0.38/32

[Peer]
PublicKey = tM2DF3FVNjf91Xcl7shK1v1mBa102e/7ZjPBv/1nVGs=
AllowedIPs = 10.0.0.38/32
PersistentKeepalive = 25
